[environment]
XDG_MENU_PREFIX = "plasma-"
QT_QPA_PLATFORM = "wayland"
ELECTRON_OZONE_PLATFORM_HINT = "auto"
QT_LOGGING_RULES = "quickshell.dbus.properties=false"
QT_QPA_PLATFORMTHEME = "kde"
QT_STYLE_OVERRIDE = "Darkly"
